const fs = require("fs");
const path = require("path");

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function planPath(outputDir, dateKey) {
  return path.join(outputDir, "plans", `hk-plan-${dateKey}.json`);
}

function writeJson(filePath, value) {
  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2), "utf8");
}

function makeReceptionPlan(dateKey, data, meta) {
  return {
    version: 1,
    savedAt: meta.generatedAt,
    data,
    staff: [],
    dutyPerson: "",
    afternoonPerson: "",
    modes: { brMode: false, zsMode: false },
    autoGenerated: true,
    meta: {
      source: "kwhotel-mail",
      targetDate: dateKey,
      generatedAt: meta.generatedAt,
      dryRun: !!meta.dryRun,
      pdfFiles: meta.pdfFiles || [],
      parserWarnings: meta.parserWarnings || [],
      historyReportCount: meta.historyReportCount || 0,
    },
  };
}

function writePlans(outputDir, plansByDate, meta) {
  const written = [];
  const skippedEmpty = [];
  for (const [dateKey, data] of Object.entries(plansByDate)) {
    if (!meta.writeEmptyPlans && Object.keys(data || {}).length === 0) {
      skippedEmpty.push(dateKey);
      continue;
    }
    const plan = makeReceptionPlan(dateKey, data, meta);
    const file = planPath(outputDir, dateKey);
    writeJson(file, plan);
    written.push({ dateKey, file, rooms: Object.keys(data).length });
  }
  writeJson(path.join(outputDir, "last-run.json"), {
    generatedAt: meta.generatedAt,
    dryRun: !!meta.dryRun,
    historyReportCount: meta.historyReportCount || 0,
    written,
    skippedEmpty,
  });
  return written;
}

module.exports = { makeReceptionPlan, planPath, writePlans };
